version: '3.8'

services:
  # Web application service
  web:
    build: .
    image: hse-contrast-checker-web:latest
    container_name: hse-contrast-checker-web
    ports:
      - "8000:8000"
    volumes:
      - ./web_output:/app/web_output
      - ./examples:/app/examples:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # CLI service (for manual runs)
  cli:
    build: .
    image: hse-contrast-checker-web:latest
    container_name: hse-contrast-checker-cli
    volumes:
      - ./examples:/app/examples:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["python", "-m", "src.cli"]
    command: ["--help"]
    profiles:
      - cli
